### ISSUE TITLE
[MB] Week of Feb 17th

### ISSUE THREAD

**Issue by bouzaghrane** [hassanobeid1994/tr_b_causal_2020#11]
- [x] Task: Continue filling in the architecture document
        - Coordinate with Hassan over what questions to address
        - Deliverable: Edits to the architecture document within the architecture branch
        - Estimate: 4 hours
        - Actual: 2 hours

- [x] Task: Work on the simulation
        - Simulate the dataset based on two data generating processes, prioritizing the first.
        - Deliverable: Push jupyter notebook into new analysis branch
        - Estimate: 3 hours
        - Actual: 3 hours

- [x] Task: Reorganize the repo
        - Make sure all files are where they need to be
        - Deliverable: Updated repository with new subfolders, renamed and moved notebooks, and updated structure graph.
        - Estimate: 2-3 hours
        - Actual: 2 hours

- [x] Task: Explore Tim's data and brainstorm causal graph
        - Deliverable: Draft causal graph in Jupyter notebook. Coordinate with Hassan.
        - Estimated: 1-2 hours
        - Actual: 1.5 hours

- [x] Task: Continue review the debugging guide
       - Deliverable: Additional comments if any on the debugging guide. If not, merge the pull request into the master branch.
       - Estimate: 1 hour
       - Actual: 1 hour

**Comment by timothyb0912** [comment]
@bouzaghrane: gentle reminder about the second task. There still isn't a branch with your jupyter notebook of the simulations.

**Comment by bouzaghrane** [comment]
@timothyb0912 Will be pushing two notebooks this afternoon before our meeting.
