### ISSUE TITLE
Generate article images from selection on observables notebook

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#184]
# What
Currently, the images in Section 2 of the article appear as if by magic.
There is no code that we know for a fact generated (i.e. saved/wrote) the images in the folder.
To be specific, there's no `fig.savefig` calls in your public notebook for saving the simulation plots.
I think the easiest way of fixing this is to simply write the images for their correct location, from the public notebook for selection on observables.

Note that this shouldn't be a final solution.
Ideally, this functionality should be separate from the public notebook.
Eventually, we should come back and have specific files for generating the images we need for our article from the selection on observables work.

cc @bouzaghrane for visibility.

**Comment by timothyb0912** [comment]
@bouzaghrane, related to the traceability of the code that generated the images, is there a bug in the code you used to generate our plots? Please respond and investigate as soon as you can.

- On November 8th, in this [commit](https://github.com/hassan-obeid/tr_b_causal_2020/blob/0d5200499590a5301e7bb72dad3f6cb0b4b919f7/article/images/histogram_selection_on_obs.png), the estimated causal effect with the correct, dependent causal graph was
**3 times larger** than the causal effect with the incorrect, independent causal graph.
- On December 19th, in this [commit](https://github.com/hassan-obeid/tr_b_causal_2020/blob/38e9070a41fed5fcf5c35819bcd9c948fcdded72/article/images/histogram_selection_on_obs.png), the estimated causal effect with the correct, dependent causal graph was
**10 times smaller** than the causal effect with the incorrect, independent causal graph. Also,
   - the magnitudes of the each distribution of causal effects has now shifted, and
   - the colors associated with each graph has now been swapped.

Given that the dependent causal graph should lead to decreased travel distance AND travel time  AND travel cost,
I expect the causal effect to be much larger with the dependent graph than with the independent graph.
I therefore assume there is a bug in the code change you introduced to edit the graphs.

**Comment by timothyb0912** [comment]
@bouzaghrane don't bother looking into this. I think it's a blessing not a bug!

I think we may have either been mistaken or wrong in the commit from November 8th.
And note we may be mistaken in the plots or mistaken in thinking the plots mean the same thing across commits.
For instance, @bouzaghrane, when did you switch to go back to the original cost / distance in the utility specification?
I think this is a good thing, but could cause the differences between plots.
Additionally, I think my comment from earlier today is wrong.

Looking at the current specification, as distance goes down, cost per distance goes up if cost is unchanged.
Since cost / distance has a negative coefficient, the utility of driving goes down, as does its aggregate share.
In the dependent graph scenario, travel time goes down because distance goes down.
Also, travel cost goes down because distance goes down.
Both of those have a negative coefficient, so utility of driving increases from that pathway.
This leads to an attenuation or possible reversal of the decrease in overall driving utility and share.
Hence the plot we see now.

I think this is great though as it illustrates our point more strongly.
There's now a non-trivial probability of the gravest of errors:
inferring the incorrect sign and making completely incorrect decisions.

**Comment by bouzaghrane** [comment]
I never changed the utility specification throughout the entire process. All I've changed was the number of simulations. The specification is similar to the one you had in your Asymmetric paper.
