### ISSUE TITLE
Save Section 2 Causal Graphs programmatically

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#194]
# What
Currently, the image files of causal graphs in Section 2 of the article are stored ad-hoc.
These graphs need to be programmatically stored so that:
- the graphs in the chapter match those in the public notebook
- edits are automatically propagated to both locations
- the plotting of the causal graphs is exercised in CI (thus ensuring at least some others can execute all code for our project)

I'm going to add programmatic storage of the graphs' image files!

cc @bouzaghrane for visibility.

**Comment by bouzaghrane** [comment]
Thanks for this @timothyb0912! Really appreciate it.

**Comment by timothyb0912** [comment]
@bouzaghrane NP!
