### ISSUE TITLE
Strengthen Section 2 results declaration

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#195]
# What
The current simulation [results](https://github.com/hassan-obeid/tr_b_causal_2020/blob/master/notebooks/final/7.0-mab-selection-on-observables-final.ipynb) indicate a small (but non-trivial) probability of a positive treatment effect (i.e. more drivers) due to moving people closer to work.
This would mean the time and cost reductions for driving out-weighted the closer distance.

We should change the statement of our results in the article to highlight the fact that
our simulations show an example where using an incorrect causal graph can
cause one to not just have the wrong magnitude of interred treatment effect but also the wrong sign.

cc @hassan-obeid and @bouzaghrane for visibility.

**Comment by bouzaghrane** [comment]
@timothyb0912 I'm back on and would like to look into this. Have you started making edits to section 2?

**Comment by timothyb0912** [comment]
Ah, sorry for the delay. Nope I haven't begun at all. If you could get to this it would be much appreciated!

I'm thinking this should be something short. Maybe editing 1 or 2 sentences. Maybe adding 1 or 2 sentences max? Could you make a PR with edits and tag me? I'll be able to review later tonight around 9pm PST.

Thanks @bouzaghrane!

**Comment by timothyb0912** [comment]
@bouzaghrane when you open your PR above, can you simply mention #198 in the body of the PR? Keep the PR's base set as master though.
