### ISSUE TITLE
[HO] Week of 2/10

### ISSUE THREAD

**Issue by hassan-obeid** [hassanobeid1994/tr_b_causal_2020#2]
- [x] Task: Address comments on docs 1-5
   - Deliverable: Newly pushed files to repo. 
   - Estimated: 1-2 hours

- [ ] Task: Start filling architecture doc with high level procedure
  - Deliverable: 
       - New architecture branch
       - Define major steps of project workflow and activities to be done in each step (e.g. data ingestion / creation, data transformation, model specification, estimation, validation, etc.).

         Keep in mind that one's project workflow should clearly denote which sub-steps / sub-workflows will produce each output that is specified in one's requirements.

  - Estimated: 3 hours

- [x] Task: Do a quick run of one substep of the workflow.
  - Deliverable: 
      - Create new analysis branch
      - In the notebook or corresponding .py file used to execute the demo, explicitly note the goal of the demo. In particular, what outputs of the script will let us know the demo was correctly executed?
      - Simulate a full data set based on causal graph
      - Run de-confounder procedure and get (even if messy) draft results
      - Check in all code used to carry out the demonstration and open a pull request for the branch.
  - Estimated: 3 hours

**Comment by bouzaghrane** [comment]
@hassanobeid1994 I created an architecture branch as I am going to start filling the doc as well.
