### ISSUE TITLE
Make Sec 2 causal graphs 1 figure

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#225]
Hey Amine,

Right now the causal graphs in section 2 are being split across pages.

Brian Coffey (who reviewed the chapter) pointed out that this isn't ideal, and it's also strange for readers who have to see the same graph two times in two different places.

Will you follow the example [here](https://tex.stackexchange.com/questions/196653/how-do-i-stack-two-figures-on-top-of-each-other-rather-than-side-to-side) to put Figure \ref{fig:DA_causal_2} through Figure \ref{fig:SR3_causal_2} into a single figure with sub-figures? You can keep the labels, they just need to go inside subfigure environments instead of in figure environments.

If you make a PR for this change, please point it at the `respond-to-brians-comments` branch and link it to this issue. 🙏🏽

**Comment by bouzaghrane** [comment]
@timothyb0912 will do.
