### ISSUE TITLE
Retrospectives

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#28]
Hey @bouzaghrane and @hassanobeid1994:

I've forgotten about this until now, but I think it's a good idea for us to set aside some time (e.g. 10 min) each week to be thoughtful and reflect on how the project is going.

To that end, I'm starting a retrospectives folder with a markdown document for each of us.

The hope is that before our weekly meetings, we'll each take ten minutes to answer:
- what is one thing that went well this week?
- what is one thing that went poorly this week?
- what is one specific way to improve our project execution process in the next week?
- what is one thing we learned this week?

**Comment by timothyb0912** [comment]
How do you all feel about this?

**Comment by bouzaghrane** [comment]
I agree on this.
