### ISSUE TITLE
[TB] Week of Feb-10

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#3]
- [x] Task: Describe the expected protocol to be followed when debugging code failures as part of this project.
  - Deliverable: A markdown file, checked into github, containing step-by-step instructions of what to do while debugging.
  - Deliverable: A pull-request to accompany the addition of the file where Amine and Hassan are tagged as reviewers.  They should review both for correctness (grammar, spelling, etc.) but also for reasonableness. Is there anything that they feel is absolutely unreasonable that we should discuss?
  - Estimate: 6 hours
  - Actual: 8 hours

**Comment by timothyb0912** [comment]
@hassanobeid1994 and @bouzaghrane: Adding you for visibility. This is what I'll do this week!

**Comment by bouzaghrane** [comment]
@timothyb0912 This might be a silly question, but is this to answer the debugging question in the architecture doc?

**Comment by timothyb0912** [comment]
@bouzaghrane Yes it is!
