### ISSUE TITLE
[MB] Week of Mar 1

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#38]
@bouzaghrane: Please fill in this weeks task list, transfer unfinished tasks from previous weeks, and close the task lists of previous weeks.

**Comment by bouzaghrane** [comment]
- [x] Work on preliminary version of the prototype of item [1](https://github.com/hassanobeid1994/tr_b_causal_2020/issues/12#issuecomment-593056084) in [#12](https://github.com/hassanobeid1994/tr_b_causal_2020/issues/12)
    - Deliverable: pushed notebook to analysis branch
    - Estimate: 8 hours
    - Actual:

- [x] Continue working on the architecture document:
    - Deliverable: pushed architecture document
    - Estimate: 3 hours
    - Actual: 2.5 hours

- [ ] Work on project workflow with Hassan
   - Deliverable: preliminary workflow of the project.
   - Estimate: 3 hours
   - Actual:

- [x] Weekly meeting
  - Estimated: 2 hrs.
  - Actual:

**Comment by timothyb0912** [comment]
@bouzaghrane Happy hump-day!
Just a gentle reminder to open pull-requests with your in-progress work for this week!

Rationale: It's better to have many small commits as opposed to one commit for a massive change because
- the git diff will be less meaningful for large changes,
- it is harder/impossible to roll back to specific points in one's work history if one batches all the changes into a single commit.

**Comment by bouzaghrane** [comment]
@timothyb0912 thank you brother! I just modified my pull request for the architecture document and tagged you and @hassanobeid1994  on it. I will be pushing things throughout the day tomorrow.

**Comment by bouzaghrane** [comment]
@timothyb0912 I am continuing to commit small changes for my work. I will submit a pull request when I have finished all the necessary commits.

**Comment by timothyb0912** [comment]
@bouzaghrane: Thanks for all the pushes with your changes!

Can you open a PR for your `simulation-code` branch so I can easily comment on it?

**Comment by bouzaghrane** [comment]
@timothyb0912 yes sir! I did yesterday. I will be committing some more today.
