### ISSUE TITLE
[MB] Week of Feb 10th

### ISSUE THREAD

**Issue by bouzaghrane** [hassanobeid1994/tr_b_causal_2020#4]
- [x] Task: Address comments on organizational docs 1-5:
  - Deliverable: Newly pushed jupytext notebooks
  - Estimate: 1 hour
  - Actual: 1 hour

- [x] Task: Start filling in the architecture document 6 with answers to questions
  - Deliverable: Pull request to the architecture branch with answers to the questions in the architecture document
  - Priority to the **Description of needed development / computational environment**
  - Estimate: 1 hour
  - Actual 1.5 hour

- [x] Task: Checking data simulation work 
  - Deliverable: New analysis branch
  - Deliverable: New pushed jupytext notebooks with defined data simulation workflow
  - Deliverable: Any input dataset used to simulate the dataset
  - Deliverable: Sample simulated dataset
  - Deliverable: Pull request for the previously mentioned elements in the analysis branch
  - Estimate: 6 hours
  - Actual: 4 hours

- [x] Task: Looking through examples about selection-on-observables:
  - Deliverable: Answers to the following questions:
  - Which 1 or 2 examples in each resource seems most similar to the selection-on-observable simulation we'd like to conduct for this project?
  - What needs to be added to each example to make it most applicable to our goals and audience?
  - What does each example do best of illustrating that we did not already create code to show?
  - What is the number one thing that is likely to be more complicated in our simulation, relative to each example, due to the fact that we're in a discrete choice setting?
  - Estimate: 7-8 hours (including reading time)
  - Actual: 4 hours

- [x] Task: Reviewing others work
- Actual: 1 hour

**Comment by timothyb0912** [comment]
Woot woot!

First, I've got a question about this plan. It sums to 16 hours currently.

Do you actually have 16 hours to devote this week to the project? It seems like a lot on top of a full-time job. If you don't plan on spending 16 hours on the project, I'd suggest amending the task list!

Second, don't spend too long on the examples about selection-on-observables. Most (if not all) of them are regression examples, so I expect them to have limited usefulness in that sense by default. The resources are also large, so you likely shouldn't read every line of the two of them.

**Comment by bouzaghrane** [comment]
I think I am able to put in the 16 hours. This is including weekend time of course. Do you suggest not accounting for the time spent on the weekend?

**Comment by bouzaghrane** [comment]
@timothyb0912 quick question: When talking about computational environment, we're talking software side (dependencies etc...), not necessarily hardware capabilities as well. right?

**Comment by timothyb0912** [comment]
@bouzaghrane Cool, the time estimation def includes weekend time. I just wanted to make sure you weren't taking on so much you'd end up burned out or overly stressed!

When talking about computational environment I'm talking about both hardware and software. Basically, if someone (including ourselves) wanted to get up and running with this project and code on a brand new computer, how do we plan to make this as painless as possible?

Here, it's best to detail things like setting up a Docker container for the project,  requirements file for pip, conda environment yaml files, etc.

**Comment by bouzaghrane** [comment]
@timothyb0912 Sounds good! Exactly what I had in mind. Just wanted to know if I should also cover hardware since there are other questions related to resource-management. But got it clarified. Thanks!

**Comment by bouzaghrane** [comment]
@timothyb0912 here are my preliminary answers to the questions about the sample examples on selection on observables. Answers are preliminary, so please let me know if I am going in the right direction:

1. Which 1 or 2 examples in each resource seems most similar to the selection-on-observable simulation we'd like to conduct for this project?
  - Causal Inference in Quantitative Econ with R: Section 10.2.4. All three examples (common cause, intermediary, and collider) are useful
  - Applied Causal Analysis: Section 12.12 (lab exercise)
2. What needs to be added to each example to make it most applicable to our goals and audience?
  - Each example lacks the visualization of a causal graph and how the causal graph helps in identifying which estimates can have a causal interpretation.
  - The examples are regression examples. We are interested in discrete choice examples and therefore need to simulate discrete choices based on specified utility functions.
  - We would need to add plot comparisons of the estimates from discrete choice methods vs. causal methods.
3. What does each example do best of illustrating that we did not already create code to show?
  - The example in Applied Causal Analysis opens by doing a descriptive exploration of the dataset. After simulating our dataset, it would be useful to add descriptive tables/plots showing the distributions of each of our variables (and comment on their reasonableness)
 - The example in Causal Inference in Quantitative Econ with R compares two model outputs where one controls for a covariate vs. one that does not.
4. What is the number one thing that is likely to be more complicated in our simulation, relative to each example, due to the fact that we're in a discrete choice setting?
 - Simulating multiple discrete choices, using specified utility functions, outside of the causal graph will be more complicated than just simulating a continuous variable.

**Comment by timothyb0912** [comment]
@bouzaghrane these answers are **exactly** what I had in mind. Let's discuss at 3pm!
