### ISSUE TITLE
[TB] Week of Mar 8

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#47]
- [x] Investigate why travel distance is zero for all transit modes.
  - Deliverable: Pushed markdown file noting the data issue (and reason if found) for future users of the data.
  - Estimated: 3 hours.
  - Actual: 1 hour.
- [x] Review Amine's revised distribution fitting code based on long-format data
  - Deliverable: Comments on the updated PR (#44)
  - Estimated: 2 hr.
  - Actual: 4 hrs.
- [x] Review Hassan's code to simulate data for a single, latently confounded utility equation.
  - Estimated: 2 hr.
  - Actual: 2. hrs.
- [x] Weekly meeting.
  - Estimated: 2 hr.
  - Actual:

**Comment by bouzaghrane** [comment]
@timothyb0912 I just wanted to check in with you about the status of task one in your list. Any luck?

**Comment by timothyb0912** [comment]
@bouzaghrane I have not looked a single second at it. It's my midweek task, so I'll have it done by tomorrow morning and tag you on it.
