### ISSUE TITLE
[MB] Week of Mar 8

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#49]
- [x] Edit independent-variable simulation code to simulate from long-format data instead of wide. Priority number 1.
   - Deliverable: Pushed commits with the code change by midweek, say 9AM Thursday.
   - Estimated: 3 hours
   - Actual: 6 hours
- [x] Respond to comments on the architecture doc. Priority number 2
   - Deliverable: Pushed commits with revisions to document or discussion on the PR saying why the comments won't/shouldn't be addressed.
   - Estimated: 2 hours
   - Actual: 2 hours
- [ ] Extend the simulation code to handle a realistic causal graph. Priority number 3.
   - Deliverable: Pushed commits (to a separate branch for this new feature) showing a prototype of taking an "intermediate" variable from realistic causal graph, and building a distribution for that variable based on its parents.
   - Estimated: 4 hours
   - Actual:
- [ ] Edit independent-variable simulation code to remove outliers, such as by using truncated distributions. Priority number 4. I think it's fine for now if you don't even get to these.
   - Deliverable: Pushed commits with pseudocode of how one plans to make the desired edits.
   - Deliverable: Pushed commits with code change, showing a visualization of the resulting distribution and evidence the outliers are gone.
   - Estimated: 2 hours
   - Actual:
- [x] Weekly Meeting
   - Estimated: 2hrs
   - Actual: 2hrs

**Comment by bouzaghrane** [comment]
@timothyb0912 got home to open this and found it already created..man you are a national treasure. <3

**Comment by bouzaghrane** [comment]
This looks good @timothyb0912 .
