### ISSUE TITLE
Selection-on-observables Simulation Goals

### ISSUE THREAD

**Issue by timothyb0912** [hassanobeid1994/tr_b_causal_2020#5]
Hey y'all, I'm starting a thread so we can collect our discussion as we clarify the explicit goals of the selection-on-observables simulation that Amine is working on.

As far as I see it, there is one goal of this simulation that we're already in agreement on:
- Demonstrating the workflow for causal inference described in section 5.2 of Brathwaite & Walker (2018).

I think this will not be of much interest to audience members of the conference, by itself, because it does not show how the workflow
- solves some problem that the audience members care about, or
- leads to some new insight / knowledge / perspective that is practically useful.

I think that we can include the following additional goal for the simulation in order to make it very interesting for the audience:
- show how causal graphs allow one to determine which estimated regression coefficients can be given interpretations in terms of causal effects.

This should be represent a large change from current practice as it means that to interpret an estimated model, one needs:
- a causal graph
- a hypothesized intervention that is being conceived of (if only implicitly) in one's causal question
- a causal question (what's the effect of ___?)

What do you all think?

**Comment by timothyb0912** [comment]
In particular, we should emphasize that researchers should “draw their assumptions before they draw their conclusions.” (See the following [online MOOC](https://www.edx.org/course/causal-diagrams-draw-your-assumptions-before-your) of the same name). The reason for this emphasis is that causal graphs enable easy determination of when a given causal effect is identified. This information is invaluable when interpreting an. estimated model.

As an illustration of this point, consider the following scenario from my time when working in transportation consulting at Cambridge Systematics.

Imagine one is a large technology company that is looking to expand its corporate campus. However, the city that one’s campus is located in will not allow the expansion to occur unless the company meets certain requirements. In particular, the company must show that despite its expansion, it is taking preventative steps to keep its drive-alone-mode share beneath X%, after the expansion.

As a result of these requirements, the company wonders “if I could move each of my employees, after the expansion, X% or Y miles closer to the campus, what would the drive alone mode share of the company be?”

This is a causal inference question that would be addressed with a mode choice model similar to the one used in my asymmetric models paper. That model featured a bike utility based on travel distance, and car and transit utilities based on travel time and travel cost. If travel distance -> travel cost and travel distance -> travel time (which it def does in the Bay Area), then one cannot interpret the travel distance coefficient causally because we control for the intermediate variables of travel cost and travel time.

We should use simulation to show that one never recovers true coefficient values, asymptotically, when in a situation where intermediate variables of a cause must be controlled for. We can contrast with a simulation where travel cost and travel time are not intermediate variables between travel distance and the mode choice. The idea would be to look at the percentage of time that the data-generating parameters fall within one’s confidence / credible interval as the training set size increases. In both cases, the model for the mode choice will be correct. What will differ is the data generating process for the explanatory variables. We will show that this difference is enough to render one’s estimates asymptotically biased in the case where the true model entails controlling for "intermediate" variables. This is analogous to the issue with multicollinearity and not being able to distinguish or allocate responsibility for an outcome.

We can base the simulations on the models in my asymmetric paper, and we can base the causal question on my work work with Cambridge Systematics.

**Comment by timothyb0912** [comment]
@bouzaghrane @hassanobeid1994

**Comment by bouzaghrane** [comment]
@timothyb0912 My understanding is that demonstrating the workflow from section 5.2 of your paper with Joan entails in itself communicating that we have to be being upfront about our causal assumptions in our causal graphs. Right?


> We can base the simulations on the models in my asymmetric paper, and we can base the causal question on my work work with Cambridge Systematics.

Do you think it would be easier since I am assuming that some defensible causal graph has already been identified?

**Comment by timothyb0912** [comment]
Updating this with conclusions from video call:

We'll have 1 to 2 simulations being done for the project and 1 analysis with real data.

All simulations and real data analysis will be based off the scenario from my 2018 asymmetric models paper with Joan.

- Simulation #1 will present a selection on observables scenario.
   - The idea is to have 2 causal graphs.
   - The model for Y is the same in both graphs.
   - There is no unobserved confounding in any graph.
   - The model for the Xs differs.
      - In the first causal graph, the Xs are generated in dependently.
      - In the second causal graph, the Xs are generated from a realistic causal graph where some Xs cause other Xs.
    - The contribution is to demonstrate that true causal effects (er, model coefficients? difference in predicted probabilities at changed X values?) are not recovered in the second scenario even though the model for Y is "well-specified." We need causal graph to accurately interpret an estimated statistical model.

- Simulation #2 will present a scenario with unobserved confounding and the use fo the de-confounder to address it.
   - Should take the realistic causal graph from simulation #1 and remove one or more observed variables.
   - The contribution is that we show how to deal with unobserved confounding in transportation context.
   - We'll contrast results from standard setting with results using the deconfounder.

- Real data analysis
   - Use the same causal graph from simulations, apply the deconfounder.
   - Show how results differ from traditional results as shown in the 2018 paper.

**Comment by timothyb0912** [comment]
Just to close the loop on your comment above @bouzaghrane, no defensible causal graph for this scenario has been created yet!
