### ISSUE TITLE
[ALL] Daily Check In

### ISSUE THREAD

**Issue by bouzaghrane** [hassanobeid1994/tr_b_causal_2020#64]
Just wanted to start this as a daily check in thread.

I added estimation code and a loop to run it N times. Will push in a few.

@timothyb0912 @hassanobeid1994

**Comment by timothyb0912** [comment]
@bouzaghrane 
I just pushed the code to demonstrate marginal independence tests for the drive alone utility's causal (sub)graph.

**Comment by timothyb0912** [comment]
@bouzaghrane I just pushed the code to the repo for simulating choices from a given pylogit model. See #65.

**Comment by bouzaghrane** [comment]
Ah this is great! I can go ahead and change those and add that to my task list. Thanks @timothyb0912 !

**Comment by timothyb0912** [comment]
@bouzaghrane no problem!

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 I pushed code to start replacing the choice simulation functions.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I started a new pull-request and branch to store work on prior and posterior predictive checks of the deconfounder's assumption of certain observed variables being independent of other observed variables, conditional on the latent confounder. See #67 .

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994  I finished adding docstring and inline comments to my code and replaced functions to simulate choice. Will be adding code to visualize results this afternoon.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
In the last two days, my main efforts for the project were reviews of your various pull requests.

Also, don't forget for tomorrow to:
- update your retrospectives
- spend 5 minutes reviewing one of our high-level planning documents (i.e. [vision](https://github.com/hassanobeid1994/tr_b_causal_2020/blob/master/references/organization/_03-Vision.md) or [requirements](https://github.com/hassanobeid1994/tr_b_causal_2020/blob/master/references/organization/_05-Requirements.md)).

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I pushed an initial draft of code to perform prior and posterior predictive conditional independence tests on the latent variable causal graph used in the deconfounder (but really any causal graph with latent variables).

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
- I found and uploaded the data from the deconfounder paper of Wang and Blei (2018).
- I updated the environment.yml file to include tensorflow and tensorflow-probability so more of the packages needed to run @hassanobeid1994 notebooks are included in the description of this project's computational environment.
- I responded to @bouzaghrane and @hassanobeid1994's discussion in #74 to clarify the workflow for finishing up the selection on observables simulation.

**Comment by bouzaghrane** [comment]
Today I worked on putting together the workflow for estimating causal effects discussed with Hassan and Tim.

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 today I started working on estimating causal effects. I fitted the data to all the available distributions on scipy. No commits yet.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I implemented the prototype of the prior predictive conditional independence tests for the deconfounder's factor model. Check out the notebook [here](https://github.com/hassanobeid1994/tr_b_causal_2020/pull/67/commits/6564afc24f0824f8f1ee391e1c049e2f66dde3ca).

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I finished implementing the predictive conditional independence tests for the deconfounder's factor model, with both prior predictive tests and posterior predictive tests. See comments on #67.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I reviewed Hassan's work today!

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I reviewed Amine's work today.

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 finished implementing a working version of the prototype to estimate causal effects. Currently reading through @timothyb0912 code.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
Finished reviewing Amine's simulations today!

**Comment by bouzaghrane** [comment]
I reviewed @timothyb0912 pull request and started looking deeper into sacred.

**Comment by timothyb0912** [comment]
I made the smallest changes to remove unnecessary list comprehensions in my deconfounder checking notebooks. @bouzaghrane and @hassanobeid1994 .

**Comment by bouzaghrane** [comment]
Today I pushed the presentation template and started looking into what needs to be refactored.
@timothyb0912 and @hassanobeid1994

**Comment by hassan-obeid** [comment]
I added more details to the planning/workflow doc (will push a version by end of day tomorrow), and started thinking about refactoring the code. @timothyb0912 @bouzaghrane

**Comment by timothyb0912** [comment]
@hassanobeid1994 : check you out!

I pushed an edited vision doc (see #85 ), left comments on Amine's presentation skeleton (see #78 ), and did a little project organization planning/review (see #84 ).

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 for your refactoring planning, please push early and push small. In other words, any thinking about refactoring that you've done should likely result in some realization like (e.g. "I need to split ___ function into smaller functions").

Capture all those realizations / thoughts in a list at the top of whatever notebook is being refactored, or in a standalone markdown file that can act as a to-do list, and push at least 1 commit per session that you sit down to think about refactoring.

The faster you document your refactoring plans/thoughts, the sooner I can give some feedback and a second pair of 👀 .

**Comment by bouzaghrane** [comment]
@timothyb0912 and @hassanobeid1994 , I pushed modified notebooks showing an increased causal effect #76 . I modified the skeleton (very rough and yet to be finished) of the presentation and reviewed the vision document from Tim.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 I responded to Amine's comments on the vision doc.

Just an fyi, given my lecture in Joan's class on Thursday morning, I may not get to editing the requirements doc before then.

**Comment by bouzaghrane** [comment]
I reviewed Hassan's #86 pull request.

@timothyb0912 @hassanobeid1994

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I finished editing the requirements doc.

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 

I finished my first take on what needs to be refactored in my notebooks.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I started a branch / pull-request to store my refactoring work (#95 ).
Also added a document in that branch (`references/refactoring/code_smells.md`) to store a list of the things I'll be looking for in my code (and yours!) that may indicate a need for refactoring or for tests to be added.

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 yesterday I started working on refactoring. Yet to push anything. I also worked some on the rpesentation.

**Comment by bouzaghrane** [comment]
@timothyb0912 and @hassanobeid1994 , today I worked on updating the architecture document and mentioned you in #6 to ask for your review and any additional input. I worked on the presentation for some time and met with Hassan for about an hour to discuss more of the outline for Thursday.

**Comment by timothyb0912** [comment]
@bouzaghrane and @hassanobeid1994 
I reviewed Amine's architecture doc work in #6 and his multinomial logit simulation code in #83.

I also added a programmatic (as opposed to visual) test to the notebook of conditional independence tests. This will enable fearless refactoring by giving a quick check that I can repeatedly run to make sure I haven't done something extremely crazy.

**Comment by hassan-obeid** [comment]
@timothyb0912 @bouzaghrane, I worked on the presentation today, and updated the investigating_deconfounder.ipynb notebook to produce plots of interest

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 I worked some more on the presentation and did some more refactoring work.

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 I started rewriting functions for refactoring in notebook 6.0

**Comment by bouzaghrane** [comment]
@timothyb0912 @hassanobeid1994 worked some more on refactoring. Details are in #89

**Comment by timothyb0912** [comment]
Closing as we haven't filled these out for months.
