### ISSUE TITLE
[MB] Week of April 5

### ISSUE THREAD

**Issue by bouzaghrane** [hassanobeid1994/tr_b_causal_2020#78]
- [x] Take two notebooks and note what needs to be refactored - [midweek]
        - Deliverable: Pushed updated notebooks with cell at top of notebook of what needs to be refactored
        - Estimate: 4hrs
        - Actual: 1hr

- [x] Push editable presentation (skeleton) [midweek]
        - Deliverable: Pushed Google Presentation with skeleton
        - Estimate: 1hr
        - Actual: 0.75hr

- [ ] Update architecture document noting requirements and vision changes
        - Deliverable: Updated pushed architecture document
        - Estimate: 2hrs
        - Actual:

- [x] Make causal effects larger
        - Deliverable: Updated pushed notebook 6.0 with different visuals
        - Estimate: 2hrs
        - Actual: 1hr

- [x] Weekly Meeting:
      - Estimate: 2hrs
      - Actual:

**Comment by timothyb0912** [comment]
@bouzaghrane for the skeleton, can you include placeholder slides based on the project requirements doc (to be updated soon, but the initial doc can be used to get started) and the vision doc (already updated)?

The placeholders obviously don't need much/any effort, just perhaps a title so we know what goes where, roughly?

**Comment by bouzaghrane** [comment]
@timothyb0912 will do!
