### ISSUE TITLE
[HO] Week of April 5

### ISSUE THREAD

**Issue by bouzaghrane** [hassanobeid1994/tr_b_causal_2020#79]
- [ ] Identify refactoring tasks for my working notebooks.
   - Deliverable: New branch with pushed notebooks showing (for each) a markdown checklist of refactoring tasks.
   - Estimate: 6 hrs.
   - Actual: 

- [x] Come up with an updated plan/workflow for our final story.
   - Deliverable: A new issue with a workflow for our story.
   - Estimate: 4 hrs.
   - Actual:  

- [ ] Star working on filling in the presentation.
   - Deliverable: Filling in slides in the presentation doc.
   - Estimate: 4 hrs.
   - Actual:  

- [x] Put together a one-notebook skeleton of our work.
   - Deliverable: Jupyter notebook with markdown specifying the high-level sections of our workflow.
   - Estimate: 4 hrs.
   - Actual:  

- [x] Weekly Meeting
   - Estimate: 2 hrs.
   - Actual:

**Comment by timothyb0912** [comment]
@hassanobeid1994 ...
