### ISSUE TITLE
[TB] Week of April 5

### ISSUE THREAD

**Issue by bouzaghrane** [hassanobeid1994/tr_b_causal_2020#80]
- [x] Update vision and requirements docs given project changes, discoveries, and discussions during prototyping.
   - Deliverable: Pushed updates to the vision and requirements docs in a new branch.
   - Estimate: 3 hrs.
   - Actual: 5 hrs.
   - Reason for delay:  
Editing the requirements doc took longer than expected as I had to think through a lot of the presentation structure, reasons for the non-goals and what they were, and various results / plots that were desired. It was good to do but took longer than I expected since I didn't have an explicit list of all those things in mind when I made the estimate.

- [ ] Identify refactoring tasks for my working notebooks.
   - Deliverable: New branch with pushed notebooks showing (for each) a markdown checklist of refactoring tasks.
   - Estimate: 6 hrs.
   - Actual: 

- [ ] Review Amine and Hassan's code / plans / presentation slides.
   - Estimate: 3 hrs.
   - Actual: 0.5 hrs so far. 

- [x] Weekly Meeting
   - Estimate: 2 hrs.
   - Actual: 2 hrs.

**Comment by timothyb0912** [comment]
Thanks @bouzaghrane!
